### ISSUE TITLE
ProtExAM fails with my protein list when run with --get_protein_aliases flag

### ISSUE THREAD

**Issue by arpelletier** [caufieldjh/protexam#2]
I ran ProtExAM with the --get_protein_aliases flag for my protein list and got the following error. It crashed after about 8%. 

> ** ProtExAM **
Retrieving UniProtKB entries for 37901 accessions.
XML output will be in multiple files.
  8% 3000/37901 [01:11<14:05, 41.26 protein entries retrieved/s]Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "./protexam/protexam/protexam.py", line 210, in <module>
    sys.exit(main())
  File "./protexam/protexam/protexam.py", line 137, in main
    pqry.download_uniprot_entries(query_list, "alias")
  File "/content/drive/My Drive/Pig Pride/2021-07-09 Comparison of 3 species genes/ProtExAM workspace/protexam/protexam/protexam_query.py", line 427, in download_uniprot_entries
    with urllib.request.urlopen(req) as r:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -5] No address associated with hostname>
  8% 3000/37901 [01:16<14:49, 39.23 protein entries retrieved/s]

**Comment by arpelletier** [comment]
Resolved. I got warnings when I installed the dependencies. I'm not sure which ones they were, but I refreshed the runtime, re-installed dependencies, and everything seemed to work as expected.
